### ISSUE TITLE
动态创建数组表单 报错

### ISSUE THREAD

**Issue by jscaden** [chenquincy/vue-dynamic-form-component#11]
请求到数据后，根据返回的参数，重新赋值descriptors 

点击添加数据后 报错 this._value 为 undefined 无法push
TypeError: Cannot read property 'push' of undefined
    at VueComponent.addArrayItem (form-item.vue?109d:205)

**Comment by chenquincy** [comment]
请提供复现demo




            
            
                
                    
                            
                                
                            
                            
                                QuincyChen
                            
                    
                        
                            
                                    邮箱：mail@quincychen.cn
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2019年12月05日 12:16，jscaden 写道： 请求到数据后，根据返回的参数，重新赋值descriptors
点击添加数据后 报错 this._value 为 undefined 无法push
TypeError: Cannot read property 'push' of undefined
at VueComponent.addArrayItem (form-item.vue?109d:205)

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/chenquincy/vue-dynamic-form-component/issues/11?email_source=notifications\u0026email_token=ACTXY6WSNMWQOJCJKGFZX23QXB6BNA5CNFSM4JVTYKIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H6GVGEQ",
"url": "https://github.com/chenquincy/vue-dynamic-form-component/issues/11?email_source=notifications\u0026email_token=ACTXY6WSNMWQOJCJKGFZX23QXB6BNA5CNFSM4JVTYKIKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H6GVGEQ",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by jscaden** [comment]
用vue-cli写的demo   麻烦大佬看一下

QuincyChen <notifications@github.com> 于2019年12月5日周四 下午12:42写道：

**Comment by chenquincy** [comment]
@jscaden 回复内容有点乱码，我删掉了，你重新贴一下demo或者demo地址

**Comment by jscaden** [comment]
<template>
  <div class="hello">
    <dynamic-form ref="dynamic-form" v-model="data" :descriptors="
descriptors"></dynamic-form>
  </div>
</template>

<script>
export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  data() {
    return {
      descriptors: {
        // 业务环境 这里肯定是空的 ，等请求到数据才会去重新赋值
        bbb: {
          type: 'array',
          label: 'array label',
          defaultField: {

          }
        },

      },
      data: {}
    }
  },
  methods: {

  },
  mounted() {
    // 这里模拟请求到数据，重新渲染
    this.descriptors = {
      // 这里是正常的，
      bbb: {
        type: 'array',
        label: '配置详情',
        required: true,
        message: 'Homepage must be a url',
        defaultField: {
          type: 'object',
          fields: {
            boolean: { type: 'boolean', label: '开关', value: true, required:
true },
          }
        }
      },
      // 这里就不正常了
      ccc: {
        type: 'array',
        label: '配置详情',
        required: true,
        message: 'Homepage must be a url',
        defaultField: {
          type: 'object',
          fields: {
            boolean: { type: 'boolean', label: '开关', value: true, required:
true },
          }
        }
      },
    }

  }
}
</script>

QuincyChen <notifications@github.com> 于2019年12月5日周四 下午4:08写道：

**Comment by chenquincy** [comment]
@jscaden 
目前还不支持在 mounted 之后动态更新descriptors，后续我有时间会考虑支持。
目前动态渲染表单有两种实现方式：
### 多个表单
一般而言，对于动态表单，初始时是会有固定部分和非固定部分，在你这个例子里面，bbb是固定部分，ccc是动态部分。
``` vue
<template>
  <div class="test">
    <dynamic-form :descriptors="bbbDescriptors" v-model="data.bbb"></dynamic-form>
    <dynamic-form v-if="cccDescriptors" :descriptors="cccDescriptors" v-model="data.ccc"></dynamic-form>
  </div>
</template>

<script>
export default {
  data () {
    return {
      data: {
        bbb: {},
        ccc: {}
      },
      bbbDescriptors: {
        bbb: {
          type: 'string',
          required: true
        }
      },
      cccDescriptors: null
    }
  },
  mounted () {
    this.cccDescriptors = {
      ccc: {
        type: 'string',
        required: true
      }
    }
  },
  methods: {}
}
</script>
```
`Object.assign({}, this.data.bbb, this.data.ccc)`就是最终结果
如果固定部分很少的话，也可以自行用 `element-ui` 实现固定部分，动态部分用这个表单组件

### 延迟渲染
另一种方式是，在获取到 descriptors 之后再渲染表单，即给表单加上 `v-if="descriptors"`
``` vue
<template>
  <div class="test">
    <dynamic-form v-if="descriptors" :descriptors="descriptors" v-model="data"></dynamic-form>
  </div>
</template>

<script>
export default {
  data () {
    return {
      data: {},
      descriptors: null
    }
  },
  mounted () {
    this.descriptors = {
      bbb: {
        type: 'string',
        required: true
      },
      ccc: {
        type: 'string',
        required: true
      }
    }
  },
  methods: {}
}
</script>
```

**Comment by jscaden** [comment]
感谢大佬
